#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL NODEJS
#=================================================
ynh_script_progression "Installing NodeJS..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SPECIFIC SETUP
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="client.config.js" --destination="$install_dir/src/client/config.js"

ynh_config_add --template="server.index.js" --destination="$install_dir/src/server/index.js"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app..."

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app npm install
	ynh_hide_warnings ynh_exec_as_app npm run package:discover
	ynh_hide_warnings ynh_exec_as_app npm run build
	ynh_hide_warnings ynh_exec_as_app npm install --save --production @osjs/pam-auth
popd

ynh_replace --match="8000" --replace="$port" --file="$install_dir/src/server/config.js"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Desktop you have accesss through your browser" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"  --wait_until="Server listening on"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
